/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Exams {
  description: string;
  id: string;
  name: string;
  year: number;
}

export interface Images {
  data: Buffer;
  id: Generated<number>;
  mime: string;
}

export interface Questions {
  answer_correct: string;
  answer_incorrect0: string;
  answer_incorrect1: string;
  answer_incorrect2: string;
  exam_id: string | null;
  id: Generated<number>;
  image: number | null;
  question: string;
}

export interface DB {
  exams: Exams;
  images: Images;
  questions: Questions;
}
